### ISSUE TITLE
Kotlin MPP support?

### ISSUE THREAD

**Issue by evgfilim1** [crackthecodeabhi/kreds#10]
Do you plan supporting [Kotlin Multiplatform](https://kotlinlang.org/docs/multiplatform.html)?

I think multiplatform communication might be implemented using https://github.com/korlibs/korio as base.

**Comment by crackthecodeabhi** [comment]
Since Kreds uses Netty underneath, its not possible to make it Kotlin multi-platform unfortunately, without considerable work.

**Comment by crackthecodeabhi** [comment]
currently the target is to implement most of the features of Redis in Kreds, hence Multi platform is not something i have on the roadmap.

**Comment by domgew** [comment]
If you come across this issue, [kedis](https://github.com/domgew/kedis) might be what you are looking for. It is using Ktor Network as its base and provides Kotlin JVM and Native (currently Linux and macOS) support. It however is in very early stages, so proceed with caution.

**Comment by nathanfallet** [comment]
@domgew Thanks for making kedis, that's exactly what I was looking for. I made the same choice of using Ktor network to make an AMQP client recently too, so I understand how it works.
