### ISSUE TITLE
More examples is required

### ISSUE THREAD

**Issue by vie10** [crackthecodeabhi/kreds#5]
Really, one example is too little for the library. I'll be grateful if you add some extra examples..

**Comment by crackthecodeabhi** [comment]
@vie10 i concur, i am planning to work on documentation on each feature with examples, by this weekend.

Thanks for raising the issue.

**Comment by vie10** [comment]
> @vie10 i concur, i am planning to work on documentation on each feature with examples, by this weekend.
> 
> Thanks for raising the issue.

I need just a messaging pipeline between applications. How I can do it with the library? Looks like I need just a stream

**Comment by vie10** [comment]
> > @vie10 i concur, i am planning to work on documentation on each feature with examples, by this weekend.
> > Thanks for raising the issue.
> 
> I need just a messaging pipeline between applications. How I can do it with the library? Looks like I need just a stream I'll be grateful if you can help me..

I already figured it out so keep your time.
