### ISSUE TITLE
How to set to connect Redis cluster

### ISSUE THREAD

**Issue by yehshuwen** [crackthecodeabhi/kreds#6]
Hi 
I want to use this Redis client to connect Redis cluster on K8s.
Do I need to set some configuration?
for example by using quarkus.redis,.client, I have to add configuration properties 
like : quarkus.redis.client-type = cluster

thank you

**Comment by crackthecodeabhi** [comment]
@yehshuwen  Kreds does not support the Redis cluster yet.
