### ISSUE TITLE
ZRANGE command returns scores when it should not

### ISSUE THREAD

**Issue by NeaGogu** [crackthecodeabhi/kreds#64]
The `Pipeline::zrange()` command always returns scores regardless of the value passed to the `withScores` parameter. 

This is most likely due to the following line which fails to check the actual value of `withScores` and always executes with `WITHSCORES` as an argument.

https://github.com/crackthecodeabhi/kreds/blob/809db319daf068a0b66a1b1476ec547bb8220dd5/src/main/kotlin/io/github/crackthecodeabhi/kreds/commands/ZSetCommands.kt#L272

**Comment by NeaGogu** [comment]
Yes, that was the issue. I will open a PR

**Comment by crackthecodeabhi** [comment]
yes, you are right, just need to add `?` for withScores like below

`withScores?.let { "WITHSCORES" }`

**Comment by crackthecodeabhi** [comment]
> Yes, that was the issue. I will open a PR

Thanks @NeaGogu

**Comment by NeaGogu** [comment]
> > Yes, that was the issue. I will open a PR
> 
> Thanks @NeaGogu

no worries :-)

**Comment by crackthecodeabhi** [comment]
> 

yes, updated my comment, here it is again 

`withScores?.let {
                if(it) "WITHSCORES" else EmptyArgument
            }`

**Comment by crackthecodeabhi** [comment]
fixed in [v0.8.1](https://github.com/crackthecodeabhi/kreds/releases/tag/0.8.1)
